### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by bdarcus** [zinit-zsh/z-a-meta-plugins#3]
I was just getting familiar with zinit, and looking for something like this.

Since this issue tracker is almost empty (why is that, BTW?), I just thought I'd submit a quick thank you for putting this together!

PS - for newbies, it might be worth mentioning how to install this?

**Comment by luxus** [comment]
good question :D how does it work

from what I understand this would replace a lot text in my config

**Comment by bdarcus** [comment]
Yes, you can do something like this to install a list of packages:

``` zsh
zinit for annexes zsh-users+fast console-tools fuzzy
```
